using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Pickup : MonoBehaviour{
    GameManager GameManager;
    // Start is called before the first frame update
    void Start(){
        GameManager = GameObject.FindGameObjectWithTag("GameManager").GetComponent<GameManager>();        
    }

    private void OnTriggerEnter(Collider otherObject){
        if(otherObject.transform.tag == "Player"){
            GameManager.currentPickup += 1;
            Destroy(this.gameObject);
        }
    }

    // Update is called once per frame
    void Update()
    {
        
    }
}
